[2025-06-18T21:11:35.228+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T21:09:27.112329+00:00 [queued]>
[2025-06-18T21:11:35.239+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T21:09:27.112329+00:00 [queued]>
[2025-06-18T21:11:35.240+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-18T21:11:35.259+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-06-18 21:09:27.112329+00:00
[2025-06-18T21:11:35.266+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2025-06-18T21:11:35.269+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_cassandra_to_clickhouse', 'load', 'manual__2025-06-18T21:09:27.112329+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/cassandra_to_clickhouse_dag.py', '--cfg-path', '/tmp/tmpxfo711uz']
[2025-06-18T21:11:35.271+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask load
[2025-06-18T21:11:35.343+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T21:09:27.112329+00:00 [running]> on host 6b28538c16e5
[2025-06-18T21:11:35.455+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_cassandra_to_clickhouse' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T21:09:27.112329+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T21:09:27.112329+00:00'
[2025-06-18T21:11:35.497+0000] {base.py:83} INFO - Using connection ID 'clickhouse_conn' for task execution.
[2025-06-18T21:11:35.502+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 53, in load_into_clickhouse
    client = get_client(host=conn.host, port=9000)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/__init__.py", line 122, in create_client
    return HttpClient(interface, host, port, username, password, database, access_token,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 165, in __init__
    super().__init__(database=database,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 70, in __init__
    self._init_common_settings(apply_server_timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 75, in _init_common_settings
    tuple(self.command('SELECT version(), timezone()', use_database=False))
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 368, in command
    response = self._raw_request(payload, params, headers, method, fields=fields, server_wait=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 481, in _raw_request
    self._error_handler(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 402, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://clickhouse:9000 returned response code 400
[2025-06-18T21:11:35.523+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_cassandra_to_clickhouse, task_id=load, execution_date=20250618T210927, start_date=20250618T211135, end_date=20250618T211135
[2025-06-18T21:11:35.539+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task load (HTTPDriver for http://clickhouse:9000 returned response code 400; 220)
[2025-06-18T21:11:35.562+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-18T21:11:35.587+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
