[2025-06-18T20:06:29.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.extract manual__2025-06-18T20:06:27+00:00 [queued]>
[2025-06-18T20:06:29.259+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.extract manual__2025-06-18T20:06:27+00:00 [queued]>
[2025-06-18T20:06:29.261+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-18T20:06:29.282+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-06-18 20:06:27+00:00
[2025-06-18T20:06:29.290+0000] {standard_task_runner.py:60} INFO - Started process 305 to run task
[2025-06-18T20:06:29.296+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_cassandra_to_clickhouse', 'extract', 'manual__2025-06-18T20:06:27+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/cassandra_to_clickhouse_dag.py', '--cfg-path', '/tmp/tmp7b438tmn']
[2025-06-18T20:06:29.300+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask extract
[2025-06-18T20:06:29.373+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_cassandra_to_clickhouse.extract manual__2025-06-18T20:06:27+00:00 [running]> on host 6b28538c16e5
[2025-06-18T20:06:29.498+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_cassandra_to_clickhouse' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T20:06:27+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T20:06:27+00:00'
[2025-06-18T20:06:29.499+0000] {cassandra_to_clickhouse_dag.py:12} INFO - Connecting to Cassandra...
[2025-06-18T20:06:29.537+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 13, in extract_from_cassandra
    conn = BaseHook.get_connection('cassandra_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `cassandra_conn` isn't defined
[2025-06-18T20:06:29.546+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_cassandra_to_clickhouse, task_id=extract, execution_date=20250618T200627, start_date=20250618T200629, end_date=20250618T200629
[2025-06-18T20:06:29.561+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task extract (The conn_id `cassandra_conn` isn't defined; 305)
[2025-06-18T20:06:29.587+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-18T20:06:29.617+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
