[2025-06-18T20:44:34.425+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T20:44:30.350862+00:00 [queued]>
[2025-06-18T20:44:34.435+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T20:44:30.350862+00:00 [queued]>
[2025-06-18T20:44:34.436+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-18T20:44:34.452+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-06-18 20:44:30.350862+00:00
[2025-06-18T20:44:34.458+0000] {standard_task_runner.py:60} INFO - Started process 842 to run task
[2025-06-18T20:44:34.462+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_cassandra_to_clickhouse', 'load', 'manual__2025-06-18T20:44:30.350862+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/cassandra_to_clickhouse_dag.py', '--cfg-path', '/tmp/tmp9pf4mg3v']
[2025-06-18T20:44:34.464+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask load
[2025-06-18T20:44:34.534+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_cassandra_to_clickhouse.load manual__2025-06-18T20:44:30.350862+00:00 [running]> on host 6b28538c16e5
[2025-06-18T20:44:34.650+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_cassandra_to_clickhouse' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T20:44:30.350862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T20:44:30.350862+00:00'
[2025-06-18T20:44:34.688+0000] {base.py:83} INFO - Using connection ID 'clickhouse_conn' for task execution.
[2025-06-18T20:44:34.716+0000] {cassandra_to_clickhouse_dag.py:41} INFO - Inserting data into ClickHouse...
[2025-06-18T20:44:34.729+0000] {transform.py:105} ERROR - Error serializing column `timestamp` into data type `DateTime`
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/temporal.py", line 134, in _write_column_binary
    column = [int(x.timestamp()) for x in column]
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/temporal.py", line 134, in <listcomp>
    column = [int(x.timestamp()) for x in column]
AttributeError: 'str' object has no attribute 'timestamp'
[2025-06-18T20:44:34.736+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 42, in load_into_clickhouse
    client.insert_df('sensor_data', df)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 710, in insert_df
    return self.insert(table,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/client.py", line 676, in insert
    return self.data_insert(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 284, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 479, in _raw_request
    error_handler(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 269, in error_handler
    raise ex
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/temporal.py", line 134, in _write_column_binary
    column = [int(x.timestamp()) for x in column]
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/datatypes/temporal.py", line 134, in <listcomp>
    column = [int(x.timestamp()) for x in column]
AttributeError: 'str' object has no attribute 'timestamp'
[2025-06-18T20:44:34.760+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_cassandra_to_clickhouse, task_id=load, execution_date=20250618T204430, start_date=20250618T204434, end_date=20250618T204434
[2025-06-18T20:44:34.775+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task load ('str' object has no attribute 'timestamp'; 842)
[2025-06-18T20:44:34.795+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-18T20:44:34.823+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
